# Generated by Django 4.0.2 on 2022-02-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title'], 'verbose_name_plural': 'Articles'},
        ),
    ]
